import { GarmentConfig, GarmentColorOption } from '../types/apparel';

export const COMMON_COLORS: GarmentColorOption[] = [
  { name: 'Onyx Black', hex: '#121214', category: 'Neutral' },
  { name: 'Vintage Washed Black', hex: '#27272a', category: 'Neutral' },
  { name: 'Crisp Studio White', hex: '#f8fafc', category: 'Neutral' },
  { name: 'Heather Cream', hex: '#f5f5f0', category: 'Neutral' },
  { name: 'Midnight Navy', hex: '#0f172a', category: 'Classic' },
  { name: 'Forest Evergreen', hex: '#14532d', category: 'Classic' },
  { name: 'Crimson Burgundy', hex: '#4c0519', category: 'Classic' },
  { name: 'Concrete Ash Gray', hex: '#94a3b8', category: 'Neutral' },
  { name: 'Desert Sand Tan', hex: '#d6c0b3', category: 'Earthy' },
  { name: 'Sage Olive', hex: '#3f6212', category: 'Earthy' },
  { name: 'Terracotta Rust', hex: '#9a3412', category: 'Earthy' },
  { name: 'Cyber Cobalt', hex: '#1d4ed8', category: 'Vibrant' },
  { name: 'Neon Acid Green', hex: '#84cc16', category: 'Vibrant' },
  { name: 'Electric Purple', hex: '#7e22ce', category: 'Vibrant' },
  { name: 'Pastel Lavender', hex: '#ddd6fe', category: 'Pastel' },
  { name: 'Bubblegum Pink', hex: '#f472b6', category: 'Vibrant' },
];

export const GARMENTS: Record<string, GarmentConfig> = {
  tshirt: {
    id: 'tshirt',
    name: 'Heavyweight Boxy Tee',
    subtitle: '240 GSM Premium Organic Cotton',
    basePrice: 28,
    availableViews: ['front', 'back', 'sleeve'],
    defaultColor: '#121214',
    fabricOptions: [
      { id: 'cotton-100', label: '100% Ring-Spun Cotton', weight: '220 GSM', description: 'Ultra-soft durable combed jersey feel' },
      { id: 'heavyweight-wash', label: 'Vintage Acid Washed', weight: '260 GSM', description: 'Distressed vintage dye finish' },
      { id: 'recycled-poly', label: 'Eco Recycled Blend', weight: '200 GSM', description: 'Sustainable performance fabric' },
    ],
    colorPresets: COMMON_COLORS,
    printBoundaries: {
      front: { x: 28, y: 22, width: 44, height: 50, label: 'Front Chest & Torso' },
      back: { x: 28, y: 20, width: 44, height: 52, label: 'Full Back Print' },
      sleeve: { x: 32, y: 30, width: 36, height: 40, label: 'Sleeve Emblem' },
    },
  },
  hoodie: {
    id: 'hoodie',
    name: 'Oversized Street Hoodie',
    subtitle: '450 GSM Heavy Fleece with Kangaroo Pocket',
    basePrice: 58,
    availableViews: ['front', 'back', 'sleeve'],
    defaultColor: '#27272a',
    fabricOptions: [
      { id: 'fleece-fleece', label: 'Heavy Fleece Cotton', weight: '450 GSM', description: 'Thick plush interior fleece insulation' },
      { id: 'french-terry', label: 'Luxury French Terry', weight: '400 GSM', description: 'Unbrushed looped back luxury weave' },
      { id: 'heavyweight-wash', label: 'Sun-Faded Vintage Fleece', weight: '480 GSM', description: 'Custom garment-dyed wash' },
    ],
    colorPresets: COMMON_COLORS,
    printBoundaries: {
      front: { x: 28, y: 24, width: 44, height: 38, label: 'Upper Chest & Pocket Area' },
      back: { x: 26, y: 22, width: 48, height: 54, label: 'Full Back Hood Graphic' },
      sleeve: { x: 30, y: 28, width: 40, height: 42, label: 'Arm Sleeve Print' },
    },
  },
  sweatshirt: {
    id: 'sweatshirt',
    name: 'Crewneck Pullover',
    subtitle: '380 GSM Ribbed Trim Sweatshirt',
    basePrice: 48,
    availableViews: ['front', 'back', 'sleeve'],
    defaultColor: '#0f172a',
    fabricOptions: [
      { id: 'fleece-fleece', label: 'Cotton Fleece Blend', weight: '380 GSM', description: 'Warm cozy daily crewneck fit' },
      { id: 'french-terry', label: 'Loopback Terry', weight: '350 GSM', description: 'Breathable high-density structure' },
    ],
    colorPresets: COMMON_COLORS,
    printBoundaries: {
      front: { x: 28, y: 22, width: 44, height: 48, label: 'Front Crew Print' },
      back: { x: 28, y: 20, width: 44, height: 50, label: 'Back Shoulders & Center' },
      sleeve: { x: 32, y: 28, width: 36, height: 40, label: 'Forearm Sleeve' },
    },
  },
  'denim-jacket': {
    id: 'denim-jacket',
    name: 'Raw Denim Trucker Jacket',
    subtitle: '14 oz Heavyweight Rigid Cotton Denim',
    basePrice: 85,
    availableViews: ['front', 'back'],
    defaultColor: '#1d4ed8',
    fabricOptions: [
      { id: 'denim-raw', label: '100% Rigid Denim', weight: '14 oz', description: 'Classic indigo selvedge structure' },
      { id: 'heavyweight-wash', label: 'Vintage Stonewashed', weight: '13.5 oz', description: 'Pre-shrunk soft faded wash' },
    ],
    colorPresets: [
      { name: 'Indigo Selvedge', hex: '#1e3a8a', category: 'Denim' },
      { name: 'Washed Stonewall Blue', hex: '#3b82f6', category: 'Denim' },
      { name: 'Raw Black Denim', hex: '#18181b', category: 'Denim' },
      { name: 'Acid Clean White', hex: '#f1f5f9', category: 'Denim' },
      { name: 'Vintage Olive Denim', hex: '#3f6212', category: 'Denim' },
    ],
    printBoundaries: {
      front: { x: 30, y: 26, width: 40, height: 40, label: 'Chest Pockets & Flaps' },
      back: { x: 25, y: 22, width: 50, height: 52, label: 'Back Denim Panel' },
    },
  },
  cap: {
    id: 'cap',
    name: 'Structured 6-Panel Snapback',
    subtitle: 'High-Profile Twill Cap with Adjustable Snap',
    basePrice: 24,
    availableViews: ['front', 'back'],
    defaultColor: '#121214',
    fabricOptions: [
      { id: 'cotton-100', label: 'Cotton Twill', weight: 'Heavy', description: 'Structured front panel with crisp shape' },
    ],
    colorPresets: COMMON_COLORS,
    printBoundaries: {
      front: { x: 25, y: 30, width: 50, height: 35, label: 'Front Crown Patch/Embroidery' },
      back: { x: 30, y: 35, width: 40, height: 30, label: 'Back Arch Above Snap' },
    },
  },
  'tote-bag': {
    id: 'tote-bag',
    name: 'Canvas Utility Tote',
    subtitle: '12 oz Heavy Canvas Bag with Reinforced Straps',
    basePrice: 18,
    availableViews: ['front', 'back'],
    defaultColor: '#f5f5f0',
    fabricOptions: [
      { id: 'cotton-100', label: 'Natural Unbleached Canvas', weight: '12 oz', description: 'Durable eco-friendly weave' },
    ],
    colorPresets: [
      { name: 'Natural Off-White', hex: '#f5f5f0' },
      { name: 'Coal Black', hex: '#18181b' },
      { name: 'Navy Canvas', hex: '#0f172a' },
      { name: 'Olive Green', hex: '#3f6212' },
      { name: 'Mustard Yellow', hex: '#d97706' },
    ],
    printBoundaries: {
      front: { x: 22, y: 25, width: 56, height: 55, label: 'Front Canvas Surface' },
      back: { x: 22, y: 25, width: 56, height: 55, label: 'Back Canvas Surface' },
    },
  },
  sweatpants: {
    id: 'sweatpants',
    name: 'Relaxed Fleece Sweatpants',
    subtitle: '360 GSM Heavyweight Jogger with Cuffed Rib',
    basePrice: 42,
    availableViews: ['front', 'back'],
    defaultColor: '#27272a',
    fabricOptions: [
      { id: 'fleece-fleece', label: 'Cotton Fleece Blend', weight: '360 GSM', description: 'Deep pockets and elastic drawstring waistband' },
    ],
    colorPresets: COMMON_COLORS,
    printBoundaries: {
      front: { x: 25, y: 25, width: 22, height: 60, label: 'Left Thigh & Leg Print' },
      back: { x: 53, y: 25, width: 22, height: 60, label: 'Right Back Calf/Thigh' },
    },
  },
  'crop-top': {
    id: 'crop-top',
    name: 'Baby Tee / Crop Top',
    subtitle: '180 GSM Fitted Stretch Cotton',
    basePrice: 22,
    availableViews: ['front', 'back'],
    defaultColor: '#f8fafc',
    fabricOptions: [
      { id: 'cotton-100', label: 'Fitted Stretch Jersey', weight: '180 GSM', description: 'Lightweight ribbed collar form-fitting tee' },
    ],
    colorPresets: COMMON_COLORS,
    printBoundaries: {
      front: { x: 28, y: 25, width: 44, height: 45, label: 'Front Chest' },
      back: { x: 28, y: 22, width: 44, height: 48, label: 'Upper Back' },
    },
  },
  shorts: {
    id: 'shorts',
    name: 'Mesh Athletic / Fleece Shorts',
    subtitle: 'Elastic Drawstring Waistband with Side Pockets',
    basePrice: 32,
    availableViews: ['front', 'back'],
    defaultColor: '#121214',
    fabricOptions: [
      { id: 'fleece-fleece', label: 'Heavy Cotton Fleece', weight: '340 GSM', description: 'Cozy plush interior with deep pockets' },
      { id: 'recycled-poly', label: 'Double Layer Mesh', weight: '220 GSM', description: 'Breathable active streetwear mesh' },
    ],
    colorPresets: COMMON_COLORS,
    printBoundaries: {
      front: { x: 20, y: 35, width: 28, height: 45, label: 'Left Leg Emblem' },
      back: { x: 52, y: 35, width: 28, height: 45, label: 'Right Leg Back' },
    },
  },
  pants: {
    id: 'pants',
    name: 'Baggy Denim Jeans / Cargo Pants',
    subtitle: '14 oz Selvedge Cotton Denim',
    basePrice: 68,
    availableViews: ['front', 'back'],
    defaultColor: '#1e3a8a',
    fabricOptions: [
      { id: 'denim-raw', label: 'Selvedge Rigid Denim', weight: '14 oz', description: 'Classic heavy structured denim' },
      { id: 'heavyweight-wash', label: 'Vintage Washed Black', weight: '13.5 oz', description: 'Sun-faded distressed wash' },
    ],
    colorPresets: [
      { name: 'Selvedge Indigo', hex: '#1e3a8a' },
      { name: 'Washer Black', hex: '#18181b' },
      { name: 'Concrete Gray', hex: '#64748b' },
      { name: 'Sand Khaki', hex: '#d6c0b3' },
      { name: 'Acid White', hex: '#f8fafc' },
    ],
    printBoundaries: {
      front: { x: 22, y: 30, width: 25, height: 55, label: 'Thigh & Knee Panel' },
      back: { x: 53, y: 25, width: 25, height: 45, label: 'Back Pocket & Calf' },
    },
  },
  shoes: {
    id: 'shoes',
    name: 'Custom High-Top Sneakers',
    subtitle: 'Canvas & Leather High-Top Street Shoes',
    basePrice: 95,
    availableViews: ['front', 'back'],
    defaultColor: '#f8fafc',
    fabricOptions: [
      { id: 'cotton-100', label: 'Heavy Canvas & Leather', weight: 'Custom', description: 'Reinforced rubber sole with canvas uppers' },
    ],
    colorPresets: COMMON_COLORS,
    printBoundaries: {
      front: { x: 25, y: 30, width: 45, height: 45, label: 'Side Ankle Canvas Panel' },
      back: { x: 30, y: 32, width: 40, height: 40, label: 'Heel & Tongue Patch' },
    },
  },
};
